languageCode = "fr"
languageName = "Français"
weight = 2
title = "Accueil"

[params]
  isoCode = "fr"
  displayName = ":fr:"
  rtl = false
  dateFormat = "2 January 2006"

[author]
  name = "Thibaut Dufour"
  image = "img/profile.png"
  headline = "Ingénieur Logiciel Freelance"
  bio = ""
  links = [
    { linkedin = "https://linkedin.com/in/thibdf" },
    { github = "https://github.com/thibdf" },
  ]
